//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Socitas.ReviewerCop {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    ///   This class was generated by MSBuild using the GenerateResource task.
    ///   To add or remove a member, edit your .resx file then rerun MSBuild.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Build.Tasks.StronglyTypedResourceBuilder", "15.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ReviewerCopAnalyzers {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ReviewerCopAnalyzers() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Socitas.ReviewerCop.ReviewerCopAnalyzers", typeof(ReviewerCopAnalyzers).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        internal static string DataClassificationOnTableCodeAction {
            get { return ResourceManager.GetString("DataClassificationOnTableCodeAction", resourceCulture); }
        }

        internal static string DataClassificationOnTableDescription {
            get { return ResourceManager.GetString("DataClassificationOnTableDescription", resourceCulture); }
        }

        internal static string DataClassificationOnTableMessageFormat {
            get { return ResourceManager.GetString("DataClassificationOnTableMessageFormat", resourceCulture); }
        }

        internal static string DataClassificationOnTableTitle {
            get { return ResourceManager.GetString("DataClassificationOnTableTitle", resourceCulture); }
        }

        internal static string EventSubscriberNamingConventionCodeAction {
            get { return ResourceManager.GetString("EventSubscriberNamingConventionCodeAction", resourceCulture); }
        }

        internal static string EventSubscriberNamingConventionDescription {
            get { return ResourceManager.GetString("EventSubscriberNamingConventionDescription", resourceCulture); }
        }

        internal static string EventSubscriberNamingConventionMessageFormat {
            get { return ResourceManager.GetString("EventSubscriberNamingConventionMessageFormat", resourceCulture); }
        }

        internal static string EventSubscriberNamingConventionTitle {
            get { return ResourceManager.GetString("EventSubscriberNamingConventionTitle", resourceCulture); }
        }

        internal static string LabelCommentForPlaceholdersDescription {
            get { return ResourceManager.GetString("LabelCommentForPlaceholdersDescription", resourceCulture); }
        }

        internal static string LabelCommentForPlaceholdersMessageFormat {
            get { return ResourceManager.GetString("LabelCommentForPlaceholdersMessageFormat", resourceCulture); }
        }

        internal static string LabelCommentForPlaceholdersTitle {
            get { return ResourceManager.GetString("LabelCommentForPlaceholdersTitle", resourceCulture); }
        }

        internal static string NoModifyInOnValidateCodeAction {
            get { return ResourceManager.GetString("NoModifyInOnValidateCodeAction", resourceCulture); }
        }

        internal static string NoModifyInOnValidateDescription {
            get { return ResourceManager.GetString("NoModifyInOnValidateDescription", resourceCulture); }
        }

        internal static string NoModifyInOnValidateMessageFormat {
            get { return ResourceManager.GetString("NoModifyInOnValidateMessageFormat", resourceCulture); }
        }

        internal static string NoModifyInOnValidateTitle {
            get { return ResourceManager.GetString("NoModifyInOnValidateTitle", resourceCulture); }
        }

        internal static string NoTodoCommentsCodeAction {
            get { return ResourceManager.GetString("NoTodoCommentsCodeAction", resourceCulture); }
        }

        internal static string NoTodoCommentsDescription {
            get { return ResourceManager.GetString("NoTodoCommentsDescription", resourceCulture); }
        }

        internal static string NoTodoCommentsMessageFormat {
            get { return ResourceManager.GetString("NoTodoCommentsMessageFormat", resourceCulture); }
        }

        internal static string NoTodoCommentsTitle {
            get { return ResourceManager.GetString("NoTodoCommentsTitle", resourceCulture); }
        }

        internal static string NoTypeOrPrefixInVariableNameDescription {
            get { return ResourceManager.GetString("NoTypeOrPrefixInVariableNameDescription", resourceCulture); }
        }

        internal static string NoTypeOrPrefixInVariableNameMessageFormat {
            get { return ResourceManager.GetString("NoTypeOrPrefixInVariableNameMessageFormat", resourceCulture); }
        }

        internal static string NoTypeOrPrefixInVariableNameTitle {
            get { return ResourceManager.GetString("NoTypeOrPrefixInVariableNameTitle", resourceCulture); }
        }

        internal static string UseSetLoadFieldsDescription {
            get { return ResourceManager.GetString("UseSetLoadFieldsDescription", resourceCulture); }
        }

        internal static string UseSetLoadFieldsMessageFormat {
            get { return ResourceManager.GetString("UseSetLoadFieldsMessageFormat", resourceCulture); }
        }

        internal static string UseSetLoadFieldsTitle {
            get { return ResourceManager.GetString("UseSetLoadFieldsTitle", resourceCulture); }
        }

        internal static string ValidateFieldAssignmentsCodeAction {
            get { return ResourceManager.GetString("ValidateFieldAssignmentsCodeAction", resourceCulture); }
        }

        internal static string ValidateFieldAssignmentsDescription {
            get { return ResourceManager.GetString("ValidateFieldAssignmentsDescription", resourceCulture); }
        }

        internal static string ValidateFieldAssignmentsMessageFormat {
            get { return ResourceManager.GetString("ValidateFieldAssignmentsMessageFormat", resourceCulture); }
        }

        internal static string ValidateFieldAssignmentsTitle {
            get { return ResourceManager.GetString("ValidateFieldAssignmentsTitle", resourceCulture); }
        }
    }
}
