//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Socitas.ReviewerCop {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    ///   This class was generated by MSBuild using the GenerateResource task.
    ///   To add or remove a member, edit your .resx file then rerun MSBuild.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Build.Tasks.StronglyTypedResourceBuilder", "15.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ReviewerCopAnalyzers {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ReviewerCopAnalyzers() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Socitas.ReviewerCop.ReviewerCopAnalyzers", typeof(ReviewerCopAnalyzers).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caption and ToolTip properties defined on page fields are not reused when the same field appears on other pages. Define these properties on the table field instead so that all pages inherit them automatically, reducing duplication and keeping translations in one place..
        /// </summary>
        internal static string CaptionTooltipOnPageDescription {
            get {
                return ResourceManager.GetString("CaptionTooltipOnPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is set on the page field but the table field does not have it. Move &apos;{0}&apos; to the table field so it is shared across all pages..
        /// </summary>
        internal static string CaptionTooltipOnPageMessageFormat {
            get {
                return ResourceManager.GetString("CaptionTooltipOnPageMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALCops: Move &apos;{0}&apos; to table field.
        /// </summary>
        internal static string CaptionTooltipOnPageMoveCodeAction {
            get {
                return ResourceManager.GetString("CaptionTooltipOnPageMoveCodeAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALCops: Move &apos;{0}&apos; to table extension.
        /// </summary>
        internal static string CaptionTooltipOnPageMoveExtCodeAction {
            get {
                return ResourceManager.GetString("CaptionTooltipOnPageMoveExtCodeAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALCops: Remove &apos;{0}&apos; from page field.
        /// </summary>
        internal static string CaptionTooltipOnPageRemoveCodeAction {
            get {
                return ResourceManager.GetString("CaptionTooltipOnPageRemoveCodeAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caption and ToolTip should be defined on the table field, not on the page field.
        /// </summary>
        internal static string CaptionTooltipOnPageTitle {
            get {
                return ResourceManager.GetString("CaptionTooltipOnPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALCops: Remove redundant DataClassification from field.
        /// </summary>
        internal static string DataClassificationOnTableCodeAction {
            get {
                return ResourceManager.GetString("DataClassificationOnTableCodeAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When DataClassification is set as a table property it applies to all fields automatically. Repeating the same classification on individual fields is redundant. Set DataClassification once on the table and remove per-field declarations..
        /// </summary>
        internal static string DataClassificationOnTableDescription {
            get {
                return ResourceManager.GetString("DataClassificationOnTableDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataClassification is already set at the table level and should not be repeated on individual fields. Remove the per-field DataClassification property..
        /// </summary>
        internal static string DataClassificationOnTableMessageFormat {
            get {
                return ResourceManager.GetString("DataClassificationOnTableMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set DataClassification as a table-level property, not per field.
        /// </summary>
        internal static string DataClassificationOnTableTitle {
            get {
                return ResourceManager.GetString("DataClassificationOnTableTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALCops: Rename to &apos;{0}&apos;.
        /// </summary>
        internal static string EventSubscriberNamingConventionCodeAction {
            get {
                return ResourceManager.GetString("EventSubscriberNamingConventionCodeAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event subscriber procedures must follow the FunctionName+EventName convention: the procedure name must end with the subscribed event name. For example, a subscriber to &apos;OnBeforeInsertEvent&apos; should be named &apos;SetRefOrderTypeInitValueOnBeforeInsertEvent&apos;..
        /// </summary>
        internal static string EventSubscriberNamingConventionDescription {
            get {
                return ResourceManager.GetString("EventSubscriberNamingConventionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event subscriber procedure &apos;{0}&apos; does not end with the event name &apos;{1}&apos; (e.g., &apos;SetRefOrderTypeInitValue{1}&apos;)..
        /// </summary>
        internal static string EventSubscriberNamingConventionMessageFormat {
            get {
                return ResourceManager.GetString("EventSubscriberNamingConventionMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event subscriber procedures must end with the event name.
        /// </summary>
        internal static string EventSubscriberNamingConventionTitle {
            get {
                return ResourceManager.GetString("EventSubscriberNamingConventionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALCops: Move opening brace to same line.
        /// </summary>
        internal static string OpenBraceOnSameLineCodeAction {
            get {
                return ResourceManager.GetString("OpenBraceOnSameLineCodeAction", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The opening brace of a field, column, or dataitem declaration must appear on the same line as the closing parenthesis. Placing the brace on a new line wastes vertical space and reduces readability..
        /// </summary>
        internal static string OpenBraceOnSameLineDescription {
            get {
                return ResourceManager.GetString("OpenBraceOnSameLineDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Opening brace &apos;{&apos; must be on the same line as the declaration, not on a new line..
        /// </summary>
        internal static string OpenBraceOnSameLineMessageFormat {
            get {
                return ResourceManager.GetString("OpenBraceOnSameLineMessageFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Opening brace must be on the same line as the declaration.
        /// </summary>
        internal static string OpenBraceOnSameLineTitle {
            get {
                return ResourceManager.GetString("OpenBraceOnSameLineTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Labels that use placeholders (%1, %2, #1, #2, etc.) must declare a Comment property that explains what each placeholder will be replaced with. This is required for correct XLIFF translations and code readability..
        /// </summary>
        internal static string LabelCommentForPlaceholdersDescription {
            get {
                return ResourceManager.GetString("LabelCommentForPlaceholdersDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label contains placeholders (%1, %2, #1, etc.) but has no Comment property. Add a Comment describing what each placeholder represents (e.g., Comment = &apos;%1 = Customer Name&apos;)..
        /// </summary>
        internal static string LabelCommentForPlaceholdersMessageFormat {
            get {
                return ResourceManager.GetString("LabelCommentForPlaceholdersMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Labels with placeholders must have a Comment property.
        /// </summary>
        internal static string LabelCommentForPlaceholdersTitle {
            get {
                return ResourceManager.GetString("LabelCommentForPlaceholdersTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global variables in AL objects create implicit coupling between procedures and make code harder to test and maintain. Prefer passing values as parameters or using local variables..
        /// </summary>
        internal static string NoGlobalVariablesDescription {
            get {
                return ResourceManager.GetString("NoGlobalVariablesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global variable &apos;{0}&apos; should be avoided. Pass variables as parameters or use local variables instead..
        /// </summary>
        internal static string NoGlobalVariablesMessageFormat {
            get {
                return ResourceManager.GetString("NoGlobalVariablesMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avoid global variables in AL objects.
        /// </summary>
        internal static string NoGlobalVariablesTitle {
            get {
                return ResourceManager.GetString("NoGlobalVariablesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALCops: Remove Modify() call.
        /// </summary>
        internal static string NoModifyInOnValidateCodeAction {
            get {
                return ResourceManager.GetString("NoModifyInOnValidateCodeAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calling Modify() inside an OnValidate trigger bypasses the expected save flow and can cause double-saves, infinite trigger loops, or data-integrity issues. The code that sets the field value is responsible for calling Modify() afterwards..
        /// </summary>
        internal static string NoModifyInOnValidateDescription {
            get {
                return ResourceManager.GetString("NoModifyInOnValidateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify() called inside an OnValidate trigger. The calling code is responsible for persisting the record; calling Modify() here can cause unexpected double-saves or infinite loops..
        /// </summary>
        internal static string NoModifyInOnValidateMessageFormat {
            get {
                return ResourceManager.GetString("NoModifyInOnValidateMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not call Modify() inside an OnValidate trigger.
        /// </summary>
        internal static string NoModifyInOnValidateTitle {
            get {
                return ResourceManager.GetString("NoModifyInOnValidateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALCops: Remove TODO comment.
        /// </summary>
        internal static string NoTodoCommentsCodeAction {
            get {
                return ResourceManager.GetString("NoTodoCommentsCodeAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO comments indicate unfinished work. All TODO comments must be resolved before a pull request is merged. Use work items or tasks to track remaining work instead..
        /// </summary>
        internal static string NoTodoCommentsDescription {
            get {
                return ResourceManager.GetString("NoTodoCommentsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO comment found. Remove or resolve all TODO comments before completing the implementation..
        /// </summary>
        internal static string NoTodoCommentsMessageFormat {
            get {
                return ResourceManager.GetString("NoTodoCommentsMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not leave TODO comments in finished code.
        /// </summary>
        internal static string NoTodoCommentsTitle {
            get {
                return ResourceManager.GetString("NoTodoCommentsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable names should be descriptive and intention-revealing. Avoid prefixes like &apos;lrec&apos;, &apos;grec&apos; and type names like &apos;Integer&apos;, &apos;Boolean&apos;, &apos;Text&apos; embedded in variable names. This follows clean code naming conventions..
        /// </summary>
        internal static string NoTypeOrPrefixInVariableNameDescription {
            get {
                return ResourceManager.GetString("NoTypeOrPrefixInVariableNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable name &apos;{0}&apos; contains a type name or Hungarian-style prefix (lrec, grec). Use descriptive, intention-revealing names instead..
        /// </summary>
        internal static string NoTypeOrPrefixInVariableNameMessageFormat {
            get {
                return ResourceManager.GetString("NoTypeOrPrefixInVariableNameMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avoid type names and Hungarian-style prefixes in variable names.
        /// </summary>
        internal static string NoTypeOrPrefixInVariableNameTitle {
            get {
                return ResourceManager.GetString("NoTypeOrPrefixInVariableNameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When reading records using FindSet, FindFirst, FindLast, or Find, use SetLoadFields to specify only the fields needed. This reduces the amount of data transferred from the database and improves performance, especially for wide tables..
        /// </summary>
        internal static string UseSetLoadFieldsDescription {
            get {
                return ResourceManager.GetString("UseSetLoadFieldsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record read using &apos;{0}&apos; without a preceding SetLoadFields call. Use SetLoadFields to load only the required fields for better performance..
        /// </summary>
        internal static string UseSetLoadFieldsMessageFormat {
            get {
                return ResourceManager.GetString("UseSetLoadFieldsMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use SetLoadFields for performance-critical record reads.
        /// </summary>
        internal static string UseSetLoadFieldsTitle {
            get {
                return ResourceManager.GetString("UseSetLoadFieldsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALCops: Replace with Validate().
        /// </summary>
        internal static string ValidateFieldAssignmentsCodeAction {
            get {
                return ResourceManager.GetString("ValidateFieldAssignmentsCodeAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direct field assignments bypass the OnValidate trigger, which may contain important business logic. Use the Validate method to ensure all validation logic is executed when assigning field values..
        /// </summary>
        internal static string ValidateFieldAssignmentsDescription {
            get {
                return ResourceManager.GetString("ValidateFieldAssignmentsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direct assignment to field &apos;{0}&apos; bypasses validation triggers. Use Validate() to ensure business rules are enforced..
        /// </summary>
        internal static string ValidateFieldAssignmentsMessageFormat {
            get {
                return ResourceManager.GetString("ValidateFieldAssignmentsMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field assignments should use Validate.
        /// </summary>
        internal static string ValidateFieldAssignmentsTitle {
            get {
                return ResourceManager.GetString("ValidateFieldAssignmentsTitle", resourceCulture);
            }
        }

        internal static string UseRestClientTitle {
            get {
                return ResourceManager.GetString("UseRestClientTitle", resourceCulture);
            }
        }

        internal static string UseRestClientMessageFormat {
            get {
                return ResourceManager.GetString("UseRestClientMessageFormat", resourceCulture);
            }
        }

        internal static string UseRestClientDescription {
            get {
                return ResourceManager.GetString("UseRestClientDescription", resourceCulture);
            }
        }

        internal static string InitializeRestClientWithHandlerTitle {
            get {
                return ResourceManager.GetString("InitializeRestClientWithHandlerTitle", resourceCulture);
            }
        }

        internal static string InitializeRestClientWithHandlerMessageFormat {
            get {
                return ResourceManager.GetString("InitializeRestClientWithHandlerMessageFormat", resourceCulture);
            }
        }

        internal static string InitializeRestClientWithHandlerDescription {
            get {
                return ResourceManager.GetString("InitializeRestClientWithHandlerDescription", resourceCulture);
            }
        }

        internal static string NoExitWithDefaultValueTitle {
            get {
                return ResourceManager.GetString("NoExitWithDefaultValueTitle", resourceCulture);
            }
        }

        internal static string NoExitWithDefaultValueMessageFormat {
            get {
                return ResourceManager.GetString("NoExitWithDefaultValueMessageFormat", resourceCulture);
            }
        }

        internal static string NoExitWithDefaultValueDescription {
            get {
                return ResourceManager.GetString("NoExitWithDefaultValueDescription", resourceCulture);
            }
        }
    }
}
