//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Socitas.AICop {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    ///   This class was generated by MSBuild using the GenerateResource task.
    ///   To add or remove a member, edit your .resx file then rerun MSBuild.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Build.Tasks.StronglyTypedResourceBuilder", "15.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AICopAnalyzers {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AICopAnalyzers() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Socitas.AICop.AICopAnalyzers", typeof(AICopAnalyzers).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caption and ToolTip properties defined on page fields are not reused when the same field appears on other pages. Define these properties on the table field instead so that all pages inherit them automatically, reducing duplication and keeping translations in one place..
        /// </summary>
        internal static string CaptionTooltipOnPageDescription {
            get {
                return ResourceManager.GetString("CaptionTooltipOnPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; should not be set on the page field. Define it on the table field instead so it is shared across all pages..
        /// </summary>
        internal static string CaptionTooltipOnPageMessageFormat {
            get {
                return ResourceManager.GetString("CaptionTooltipOnPageMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALCops: Move &apos;{0}&apos; to table field.
        /// </summary>
        internal static string CaptionTooltipOnPageMoveCodeAction {
            get {
                return ResourceManager.GetString("CaptionTooltipOnPageMoveCodeAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALCops: Move &apos;{0}&apos; to table extension.
        /// </summary>
        internal static string CaptionTooltipOnPageMoveExtCodeAction {
            get {
                return ResourceManager.GetString("CaptionTooltipOnPageMoveExtCodeAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALCops: Remove &apos;{0}&apos; from page field.
        /// </summary>
        internal static string CaptionTooltipOnPageRemoveCodeAction {
            get {
                return ResourceManager.GetString("CaptionTooltipOnPageRemoveCodeAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caption and ToolTip should be defined on the table field, not on the page field.
        /// </summary>
        internal static string CaptionTooltipOnPageTitle {
            get {
                return ResourceManager.GetString("CaptionTooltipOnPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &quot;Rest Client&quot; codeunit should be initialized with a custom handler codeunit defined in the current app. This ensures HTTP client configuration (timeouts, default headers, retry policies) is centralized and consistent across all HTTP calls. Without a local handler, the default system handler is used, which may not match the app&apos;s requirements..
        /// </summary>
        internal static string InitializeRestClientWithHandlerDescription {
            get {
                return ResourceManager.GetString("InitializeRestClientWithHandlerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RestClient.Initialize() must pass a handler codeunit defined in the current app. Create a codeunit that implements the &quot;Http Client Handler&quot; interface to centralize HTTP client configuration..
        /// </summary>
        internal static string InitializeRestClientWithHandlerMessageFormat {
            get {
                return ResourceManager.GetString("InitializeRestClientWithHandlerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rest Client must be initialized with a handler codeunit from the current app.
        /// </summary>
        internal static string InitializeRestClientWithHandlerTitle {
            get {
                return ResourceManager.GetString("InitializeRestClientWithHandlerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When a procedure&apos;s exit statement passes the type&apos;s default value (false for Boolean, 0 for Integer, &apos;&apos; for Text/Code), the explicit value is redundant. A bare exit; (without an argument) already returns the default. Removing the redundant value improves readability..
        /// </summary>
        internal static string NoExitWithDefaultValueDescription {
            get {
                return ResourceManager.GetString("NoExitWithDefaultValueDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to exit() is called with the default value &apos;{0}&apos;. Use a bare exit; instead — AL returns the type&apos;s default automatically..
        /// </summary>
        internal static string NoExitWithDefaultValueMessageFormat {
            get {
                return ResourceManager.GetString("NoExitWithDefaultValueMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not use exit() with an explicit default value.
        /// </summary>
        internal static string NoExitWithDefaultValueTitle {
            get {
                return ResourceManager.GetString("NoExitWithDefaultValueTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global variables in AL objects create implicit coupling between procedures and make code harder to test and maintain. Prefer passing values as parameters or using local variables..
        /// </summary>
        internal static string NoGlobalVariablesDescription {
            get {
                return ResourceManager.GetString("NoGlobalVariablesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global variable &apos;{0}&apos; should be avoided. Pass variables as parameters or use local variables instead..
        /// </summary>
        internal static string NoGlobalVariablesMessageFormat {
            get {
                return ResourceManager.GetString("NoGlobalVariablesMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avoid global variables in AL objects.
        /// </summary>
        internal static string NoGlobalVariablesTitle {
            get {
                return ResourceManager.GetString("NoGlobalVariablesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALCops: Move opening brace to same line.
        /// </summary>
        internal static string OpenBraceOnSameLineCodeAction {
            get {
                return ResourceManager.GetString("OpenBraceOnSameLineCodeAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The opening brace of a field, column, or dataitem declaration must appear on the same line as the closing parenthesis. Placing the brace on a new line wastes vertical space and reduces readability..
        /// </summary>
        internal static string OpenBraceOnSameLineDescription {
            get {
                return ResourceManager.GetString("OpenBraceOnSameLineDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening brace &apos;{{&apos; must be on the same line as the declaration, not on a new line..
        /// </summary>
        internal static string OpenBraceOnSameLineMessageFormat {
            get {
                return ResourceManager.GetString("OpenBraceOnSameLineMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening brace must be on the same line as the declaration.
        /// </summary>
        internal static string OpenBraceOnSameLineTitle {
            get {
                return ResourceManager.GetString("OpenBraceOnSameLineTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &quot;Rest Client&quot; codeunit provides a higher-level abstraction over raw HTTP types (HttpClient, HttpRequestMessage, HttpResponseMessage, HttpContent, HttpHeaders). It simplifies HTTP communication by handling content creation, request execution, and response parsing in fewer lines of code with less boilerplate..
        /// </summary>
        internal static string UseRestClientDescription {
            get {
                return ResourceManager.GetString("UseRestClientDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable of type &apos;{0}&apos; detected. Use the &quot;Rest Client&quot; codeunit instead of raw HTTP types for simpler, more maintainable HTTP communication..
        /// </summary>
        internal static string UseRestClientMessageFormat {
            get {
                return ResourceManager.GetString("UseRestClientMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the &quot;Rest Client&quot; codeunit instead of raw HTTP types.
        /// </summary>
        internal static string UseRestClientTitle {
            get {
                return ResourceManager.GetString("UseRestClientTitle", resourceCulture);
            }
        }
    }
}
